title: A Man Learns Code
navbar_title: A Man Learns Code

author:
  name: Chris Dinh # Your name
  email: chaudvb95uc@gmail.com

description: Software engineering chatter and some tools # description of your site

url: "https://jekyll-academic.netlify.app" # The base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # The subpath of your site, e.g. /blog

jekyllacademic:
  homepage_title: "Hello world" # Your homepage title
  disqusname: # Your disqus sitename
  footer: Chris Dinh, 2023 # Your name, Year
  contentlicense: "MIT" # Choose either one of these to put: MIT, Commons Clause, CC BY 4.0, CC BY-NC 4.0, CC BY-ND 4.0, CC BY-NC-ND 4.0, CC BY-NC-SA 4.0, CC BY-NC-SA 4.0, CC BY-SA 4.0
  socials:
    github: chaudinh # Your github username

# No need to edit this part, however if you want to, that's fine as well

permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
